#!/bin/sh

if [ ! -f mapslicer.py  -o  ! -d mapslicer ];
then
    echo "The script must be invoked from the mapslicer root directory."
    exit 1
fi

PYTHON=`which python`
SANDBOX=`mktemp -d`
FILES="mapslicer.py mapslicer README.txt deploy/linux/mapslicer.desktop \
       resources/icon.png"

# get mapslicer version
VERSION=`$PYTHON -c 'import mapslicer; print mapslicer.version.replace(" ",".")'`

# name the archive and directory according to debian policy
ARCHNAME="MapSlicer-$VERSION"

# create sandbox
mkdir "$SANDBOX/$ARCHNAME"

# copy project files and archive in there
tar cvzf "$SANDBOX/$ARCHNAME/$ARCHNAME.tar.gz" --exclude='.svn' --exclude='*.pyc' $FILES
tar xzf "$SANDBOX/$ARCHNAME/$ARCHNAME.tar.gz" -C "$SANDBOX/$ARCHNAME"

# copy our debian files as well
cp -r deploy/linux/debian "$SANDBOX/$ARCHNAME"

# update version and date
CURDATE=`date -R`
sed -i -e "s/\\\$VERSION/$VERSION/g" -e "s/\\\$DATE/$CURDATE/g" \
    "$SANDBOX/$ARCHNAME/debian/changelog"

# build the .deb
(cd "$SANDBOX/$ARCHNAME"; dpkg-buildpackage -d)

# copy it
cp "$SANDBOX"/*.deb .

# clean up
rm -rf "$SANDBOX"
